config/routes.rb
Rails.application.routes.draw do
  resources :add_order_to_shipping_addresses
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}, controllers: { :sessions => "custom_sessions" }  

  resources :orders
  resources :search, only: [:index]  
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]  
  resources :products do 
      collection do
      put :update_multiple
    end
  end

  #get '/button3', to: 'carts#place_order', as: 'button3'

  put 'orders', to: 'orders#update'
  get 'products/:id', to: 'products#show', as: 'product_show'

  get 'billing', to: 'orders#billing'
  get 'checkout', to: 'carts#checkout'

  get 'cpus', to: 'pages#cpus'
  get 'keyboards', to: 'pages#keyboards'
  get 'monitors', to: 'pages#monitors'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  get 'user_page', to: 'user_pages#user_page'
  get 'user_billing', to: 'user_pages#user_billing'
  get 'user_shipping', to: 'user_pages#user_shipping'
  get 'user_settings', to: 'user_pages#user_settings'
  get 'user_order_history', to: 'user_pages#user_order_history'

  get 'admin', to: 'admins#admin'
  get 'admin/inventory', to: 'admins#admin_inventory'
  get 'admin/orders', to: 'admins#admin_orders'  

  root to: 'pages#home'   
end

app/views/admins/admin.html.erb
<h1> 
  <%= link_to "Home", root_path, class: "admin-link", id:"admin-heading"%>   
</h1>

<div class="row">
  <div class="col-md-3" >
    <div class="col-md-12 col-lg-4 ">
      <%= link_to "Orders", admin_orders_path, class: "admin-link"%>
      <br>
      <%= link_to "Inventory", admin_inventory_path, class: "admin-link"%>
   </div>
  </div>
</div>

app/views/admins/admin_inventory.html.erb
<!doctype html>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>Album example for Bootstrap</title>

    <!-- Bootstrap core CSS 
    <link href="../../../../dist/css/bootstrap.min.css" rel="stylesheet"> -->

    <!-- Custom styles for this template 
    <link href="album.css" rel="stylesheet"> --> 

  </head>  

  <body>
   <div class="row admin-nav">  
    <%= link_to "Home", root_path, class: "admin-link" %>
    <div> 
     <i class="fa fa-caret-right" id="admin-nav-icon"></i>
    </div>
    <%= link_to "Admin", admin_path, class: "admin-link" %>   
      <div> 
       <i class="fa fa-caret-right" id="admin-nav-icon"></i>
      </div>
    <%= link_to "Inventory", admin_inventory_path, class: "admin-link" %>   
  </div>
    <div class="container-fluid">          
      <div class="container">
        <div class="row">
          <%= form_tag update_multiple_products_path, id:"myForm", method: :put do  %>
            <table class="inventory_table">               
              <thead class="thead-dark">
                <th></th>
                <th>Image</th>
                <th>UPC</th>
                <th>Name</th>
                <th>Brand</th>
                <th>Category</th>
                <th>Stock</th>
                <th>Status</th>
                <th>Price</th>
                <th></th>
                <th></th>             
              </thead>
              <% @products.each do |product| %>
                <%= fields_for "products[]", product do |f| %>
                <% if product.errors.any? %>
                  <div id="error_explanation">
                    <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>
                    <ul>
                    <% product.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                    </ul>
                  </div>
                <% end %>
                <tr>                      
                  <td class="inventory_row"><%= check_box_tag 'product_ids[]', product.id%></td>
                  <td><%= link_to (image_tag product.main_image ), product_path(product) unless product.main_image.nil?  %></td>  
                  <td class="inventory_row"><%= f.text_field :upc, size: "8", class: "td" %></td> 
                  <td class="inventory_row"><%= f.text_field :name, size: "12", class: "td" %></td>                  
                  <td class="inventory_row"><%= f.text_field :brand, size: "10", class: "td" %></td>  
                  <td class="inventory_row"><%= f.text_field :category, size: "10", class: "td" %></td>   
                  <td class="inventory_row"><%= f.number_field :quantity,  class: "td number_field" %></td>
                  <td class="inventory_row"><div class="td-text"><%= link_to "#{product.status}" %></div></td> 
                  <td class="inventory_row"><%= f.number_field :price,  class: "td price_number_field" %></td>
                </tr>
                <% end %>              
              <% end %>  
            </table>
           <%= submit_tag "Update All" %>
          <% end %>   
        </div>              
      </div>                   
    </div>     
   </div>
  </body>

  <footer class="text-muted">
    <%= render 'shared/application_footer' %>
  </footer>
</html>

app/views/admins/admin_orders.html.erb
<div class="row admin-nav">  
  <%= link_to "Home", root_path, class: "admin-link" %>
  <div> 
    <i class="fa fa-caret-right" id="admin-nav-icon"></i>
  </div>
  <%= link_to "Admin", admin_path, class: "admin-link" %>   
  <div> 
    <i class="fa fa-caret-right" id="admin-nav-icon"></i>
  </div>
  <%= link_to "Orders", admin_orders_path, class: "admin-link" %>   
</div>


<p id="notice"><%= notice %></p>

<table class="table">
  <thead class="thead-dark">
    <th>Order</th>
    <th>Date Created</th>
    <th>Tracking</th>
    <th>Total</th>
    <th>Status</th>
    <th></th>
  </thead>

  <tbody>    
    <% @orders.each do |order| %>
      <tr>
        <td><%= link_to "#{order.id}", order %></td>
        <td><%= order.created_at.strftime("%m-%d-%Y") %></td>        
        <td><%= link_to "#{order.tracking}" %></td>
        <td><%= order.total %></td>
        <td><%= order.order_status_id %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>        
      </tr>        
    <% end %>
  </tbody>
</table>