config/routes.rb
Rails.application.routes.draw do
  resources :add_order_to_shipping_addresses
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}, controllers: { :sessions => "custom_sessions" }  

  resources :orders
  resources :search, only: [:index]  
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]  
  resources :products do 
      collection do
      put :update_multiple
    end
  end

  #get '/button3', to: 'carts#place_order', as: 'button3'

  put 'orders', to: 'orders#update'
  get 'products/:id', to: 'products#show', as: 'product_show'

  get 'billing', to: 'orders#billing'
  get 'checkout', to: 'carts#checkout'

  get 'cpus', to: 'pages#cpus'
  get 'keyboards', to: 'pages#keyboards'
  get 'monitors', to: 'pages#monitors'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  get 'user_page', to: 'user_pages#user_page'
  get 'user_billing', to: 'user_pages#user_billing'
  get 'user_shipping', to: 'user_pages#user_shipping'
  get 'user_settings', to: 'user_pages#user_settings'
  get 'user_order_history', to: 'user_pages#user_order_history'

  get 'admin', to: 'admins#admin'
  get 'admin/inventory', to: 'admins#admin_inventory'
  get 'admin/orders', to: 'admins#admin_orders'  

  root to: 'pages#home'   
end

app/views/shared/_application_footer.html.erb
<div class="mastfoot">
  <div class="inner">
    <div><%= link_to "About", about_path %></div>
    <div><%= link_to "Contact", contact_path %></div>
    <p>Copyright Symbol</p>
  </div>
</div>

app/views/shared/_application_nav.html.erb
<!-- TODO -->
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
  <a class="navbar-brand" <%= link_to "Home", root_path %></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample03" aria-controls="navbarsExample03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExample03">
    <ul class="navbar-nav mr-auto">
     <li class="nav-item dropdown active">
        <a class="nav-link dropdown-toggle" href="#" id="dropdown03" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Core Components</a>
        <div class="dropdown-menu" aria-labelledby="dropdown03">
          <a class="dropdown-item" <%= link_to "CPUs", cpus_path %> </a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>          
      <li class="nav-item active">
        <% %>
        <a class="nav-link" <%= link_to "Keyboards", keyboards_path %> <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" <%= link_to "Monitors", monitors_path %> <span class="sr-only">(current)</span></a>
      </li>            
    </ul>
    <div>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
        <%= link_to "Admin", admin_path, class:'nav-link' if logged_in?(:admin) %>
        </li>  
        <li class="nav-item active">        
          <%= login_helper 'nav-link' %>
        </li>  
        <li class="nav-item active">
          <%= link_to fa_icon('user'), user_page_path, id: "nav-icon" if logged_in?(:admin, :registered_user) %>
        </li>
        <li class="nav-item active">
          <%= link_to fa_icon('shopping-cart'), cart_path, id: "nav-icon" %>  
        </li>            
      <li class="nav-item active">
        <form class="form-inline my-2 my-md-0">
          <%= form_tag products_path, method: :get do %>   
          <div class="form-control" >         
            <%= text_field_tag :query, params[:query], class: 'form-control'%>
            <%= submit_tag "Search", name: nil, class: 'form-control' %>      
          </div>
          <% end %>  
       </li>
      </form>
    </div>
  </div>
</nav>

app/views/shared/_product_row.html.erb
<div class="col-md-3" ">               
  <div class="card product-card mb-3 " ">
    <div class="box-shadow" ">
      <%= link_to (image_tag product.main_image ), product_path(product) unless product.main_image.nil?  %>
      <div class="col-xs-8">
        <h4><%= product.name %></small></h4>
      </div>
      <div class="col-xs-4">
        <%= form_for order_item, remote: true do |f| %>
        <h4 >Price:<%= number_to_currency product.price, class: "product-price"%></h4>
          <div class="input-group">
            <%= f.number_field :quantity, value: 1, class: "form-control", min: 1 %>
            <div class="input-group-btn">
              <%= f.hidden_field :product_id, value: product.id %>
              <%= f.submit "Add to Cart", class: "btn btn-primary" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>