config/routes.rb
Rails.application.routes.draw do
  resources :add_order_to_shipping_addresses
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}, controllers: { :sessions => "custom_sessions" }  

  resources :orders
  resources :search, only: [:index]  
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]  
  resources :products do 
      collection do
      put :update_multiple
    end
  end

  #get '/button3', to: 'carts#place_order', as: 'button3'

  put 'orders', to: 'orders#update'
  get 'products/:id', to: 'products#show', as: 'product_show'

  get 'billing', to: 'orders#billing'
  get 'checkout', to: 'carts#checkout'

  get 'cpus', to: 'pages#cpus'
  get 'keyboards', to: 'pages#keyboards'
  get 'monitors', to: 'pages#monitors'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  get 'user_page', to: 'user_pages#user_page'
  get 'user_billing', to: 'user_pages#user_billing'
  get 'user_shipping', to: 'user_pages#user_shipping'
  get 'user_settings', to: 'user_pages#user_settings'
  get 'user_order_history', to: 'user_pages#user_order_history'

  get 'admin', to: 'admins#admin'
  get 'admin/inventory', to: 'admins#admin_inventory'
  get 'admin/orders', to: 'admins#admin_orders'  

  root to: 'pages#home'   
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!

  def show
    @order_items = current_order.order_items
  end  

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart_row.html.erb
<div class="row">
  <div class="col-md-4">
    <%= link_to (image_tag product.main_image ), product_path(product) unless product.main_image.nil?  %>
  </div>
  <div class="col-md-8" class="info">
    <div class="info">
      <div class="row">
        <div class="col-md-5 product-name">
          <div class="product-name">
            <%= product.name %>        
          </div>
        </div>
        <div class="col-md-4 quantity">          
          <%= form_for order_item, remote: true do |f| %>
            <div class="row">
              <div class="col-xs-4">
                <%= f.number_field :quantity, value: order_item.quantity.to_i, class: "form-control", min: 1 %>
                <%= f.hidden_field :product_id, value: product.id %>
              </div>
              <div class="col-xs-8 text-right">
                <div class="btn-group" >
                  <%= f.submit "Update Quantity", class: "btn btn-primary" %>
                  <%= link_to "Delete", order_item, { data: { confirm: "Are you sure you wish to delete the product '#{order_item.product.name}' from your cart?" }, method: :delete, remote: true, class: "btn btn-danger" } %>
                </div>
              </div>
            </div>        
          <% end %>          
        </div>
        <div class="col-md-3 price">
          <span><%= order_item.unit_price %>
          </span>
        </div>
      </div>
    </div>
  </div>
</div>

 

app/views/carts/_shopping_cart.html.erb
<% if !@order_item.nil? && @order_item.errors.any? %>
  <div class="alert alert-danger">
    <ul>
    <% @order_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<% if @order_items.size == 0 %>
  <p class="text-center">
    There are no items in your shopping cart.  Please <%= link_to "go back", root_path %> and add some items to your cart.
  </p>
<% else %>
  <% @order_items.each do |order_item| %>    
    <%= render 'carts/cart_row', product: order_item.product, order_item: order_item, show_total: true %>        
  <% end %>  
  
  <h1>Total: <%= grand_total = @order_items.sum(&:total_price) %> </h1>
  <%= grand_total.inspect %>
  <hr>
<% end %>

app/views/carts/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shopping Cart</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  
</head>
<body>
  <main class="page">
    <section class="shopping-cart dark">
      <div class="container">
        <div class="block-heading">
          <h2>Shopping Cart</h2>          
        </div>
        <div class="content">
          <div class="row">
            <div class="col-md-12 col-lg-8">
              <div class="items">
                <div class="product">
                  <%= render 'shopping_cart' %>
                </div>
              </div>
            </div>
            <div class="col-md-12 col-lg-4">
              <div class="summary">
                <h3>Summary</h3>
                <div class="summary-item"><span class="text">Subtotal</span><span class="price">$<%= subtotal = @order_items.sum(&:total_price) %></span></div>
                <div class="summary-item"><span class="text">Discount</span><span class="price">$<%= discount = 0 %></span></div>
                <div class="summary-item"><span class="text">Shipping</span><span class="price">$<%= shipping = 10 %> </span></div>
                <div class="summary-item"><span class="text">Total</span><span class="price">$<%= subtotal + shipping %></span></div>
                <%= link_to "Checkout", billing_path, class:"btn btn-primary btn-lg btn-block" %>                
              </div>
            </div>
          </div> 
        </div>
      </div>
    </section>
  </main>
</body>
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</body>
</html>